[2024-06-28T09:57:47.584+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T09:57:47.720+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_weather_data manual__2024-06-28T09:52:39.741132+00:00 [queued]>
[2024-06-28T09:57:47.727+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_weather_data manual__2024-06-28T09:52:39.741132+00:00 [queued]>
[2024-06-28T09:57:47.727+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-28T09:57:47.740+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2024-06-28 09:52:39.741132+00:00
[2024-06-28T09:57:47.747+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T09:57:47.749+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_weather_data', 'manual__2024-06-28T09:52:39.741132+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmplkp5cp0c']
[2024-06-28T09:57:47.750+0000] {standard_task_runner.py:63} INFO - Started process 95 to run task
[2024-06-28T09:57:47.751+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask fetch_weather_data
[2024-06-28T09:57:47.794+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.fetch_weather_data manual__2024-06-28T09:52:39.741132+00:00 [running]> on host 96605e21a9b4
[2024-06-28T09:57:47.885+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T09:52:39.741132+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T09:52:39.741132+00:00'
[2024-06-28T09:57:47.887+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T09:57:47.888+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T09:57:47.888+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fetch_weather_data() missing 1 required positional argument: 'city'
[2024-06-28T09:57:47.896+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=weather_data_pipeline, task_id=fetch_weather_data, run_id=manual__2024-06-28T09:52:39.741132+00:00, execution_date=20240628T095239, start_date=20240628T095747, end_date=20240628T095747
[2024-06-28T09:57:47.908+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task fetch_weather_data (fetch_weather_data() missing 1 required positional argument: 'city'; 95)
[2024-06-28T09:57:47.925+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T09:57:47.943+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T09:57:47.948+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
