[2024-06-28T22:58:22.072+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T22:58:22.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.predict_weather manual__2024-06-28T22:57:55.205119+00:00 [queued]>
[2024-06-28T22:58:22.117+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.predict_weather manual__2024-06-28T22:57:55.205119+00:00 [queued]>
[2024-06-28T22:58:22.117+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T22:58:22.135+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_weather> on 2024-06-28 22:57:55.205119+00:00
[2024-06-28T22:58:22.149+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=228) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T22:58:22.151+0000] {standard_task_runner.py:63} INFO - Started process 234 to run task
[2024-06-28T22:58:22.152+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'predict_weather', 'manual__2024-06-28T22:57:55.205119+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpt98s1rpc']
[2024-06-28T22:58:22.155+0000] {standard_task_runner.py:91} INFO - Job 138: Subtask predict_weather
[2024-06-28T22:58:22.217+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.predict_weather manual__2024-06-28T22:57:55.205119+00:00 [running]> on host ed120f20c26b
[2024-06-28T22:58:22.425+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='predict_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T22:57:55.205119+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T22:57:55.205119+00:00'
[2024-06-28T22:58:22.429+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T22:58:22.452+0000] {warnings.py:112} WARNING - /opt/***/scripts/predict.py:13: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['temperature_2m'].fillna(method='ffill', inplace=True)

[2024-06-28T22:58:22.501+0000] {python.py:237} INFO - Done. Returned value was: ./predicted_weather_20240628225822.csv
[2024-06-28T22:58:22.501+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T22:58:22.542+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=predict_weather, run_id=manual__2024-06-28T22:57:55.205119+00:00, execution_date=20240628T225755, start_date=20240628T225822, end_date=20240628T225822
[2024-06-28T22:58:22.617+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T22:58:22.646+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T22:58:22.647+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
