[2024-06-28T04:56:21.919+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T04:56:21.951+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.predict_weather manual__2024-06-28T04:56:15.850710+00:00 [queued]>
[2024-06-28T04:56:21.964+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.predict_weather manual__2024-06-28T04:56:15.850710+00:00 [queued]>
[2024-06-28T04:56:21.964+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T04:56:21.981+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_weather> on 2024-06-28 04:56:15.850710+00:00
[2024-06-28T04:56:21.987+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=97) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T04:56:21.988+0000] {standard_task_runner.py:63} INFO - Started process 99 to run task
[2024-06-28T04:56:21.989+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'predict_weather', 'manual__2024-06-28T04:56:15.850710+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpv8x6gdx3']
[2024-06-28T04:56:21.990+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask predict_weather
[2024-06-28T04:56:22.035+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.predict_weather manual__2024-06-28T04:56:15.850710+00:00 [running]> on host 49f46dd2f77d
[2024-06-28T04:56:22.131+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='predict_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T04:56:15.850710+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T04:56:15.850710+00:00'
[2024-06-28T04:56:22.133+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T04:56:22.936+0000] {warnings.py:112} WARNING - /opt/***/scripts/predict.py:13: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['temperature_2m'].fillna(method='ffill', inplace=True)

[2024-06-28T04:56:22.960+0000] {python.py:237} INFO - Done. Returned value was: ./data/predicted_weather_20240628045622.csv
[2024-06-28T04:56:22.961+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T04:56:22.993+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=predict_weather, run_id=manual__2024-06-28T04:56:15.850710+00:00, execution_date=20240628T045615, start_date=20240628T045621, end_date=20240628T045622
[2024-06-28T04:56:23.046+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T04:56:23.062+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T04:56:23.066+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
