[2024-06-28T11:00:34.055+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T11:00:34.076+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.predict_weather manual__2024-06-28T11:00:23.233760+00:00 [queued]>
[2024-06-28T11:00:34.086+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.predict_weather manual__2024-06-28T11:00:23.233760+00:00 [queued]>
[2024-06-28T11:00:34.087+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T11:00:34.105+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_weather> on 2024-06-28 11:00:23.233760+00:00
[2024-06-28T11:00:34.114+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T11:00:34.116+0000] {standard_task_runner.py:63} INFO - Started process 102 to run task
[2024-06-28T11:00:34.115+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'predict_weather', 'manual__2024-06-28T11:00:23.233760+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpljligw4a']
[2024-06-28T11:00:34.117+0000] {standard_task_runner.py:91} INFO - Job 112: Subtask predict_weather
[2024-06-28T11:00:34.174+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.predict_weather manual__2024-06-28T11:00:23.233760+00:00 [running]> on host c0297b00fc40
[2024-06-28T11:00:34.298+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='predict_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T11:00:23.233760+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T11:00:23.233760+00:00'
[2024-06-28T11:00:34.300+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T11:00:34.316+0000] {warnings.py:112} WARNING - /opt/***/scripts/predict.py:13: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['temperature_2m'].fillna(method='ffill', inplace=True)

[2024-06-28T11:00:34.336+0000] {python.py:237} INFO - Done. Returned value was: ./predicted_weather.csv
[2024-06-28T11:00:34.336+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T11:00:34.361+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=predict_weather, run_id=manual__2024-06-28T11:00:23.233760+00:00, execution_date=20240628T110023, start_date=20240628T110034, end_date=20240628T110034
[2024-06-28T11:00:34.412+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T11:00:34.427+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T11:00:34.431+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
